### ISSUE TITLE
Compatibility issue with iOS <= 6

### ISSUE THREAD

**Issue by PoomSmart** [hbang/libcephei#19]
-[UIViewController edgesForExtendedLayout] doesn't exist in iOS <= 6. Also any other iOS 7+ API, earlier OS won't accept them and therefore crashing occurs.

**Comment by kirb** [comment]
Fixed all of them that I could see. Know of any I missed?

**Comment by PoomSmart** [comment]
@kirb Yes, -tintColor selector does not exist in iOS <= 6 but HBLinkTableCell tries to use it.
https://github.com/hbang/libcephei/blob/master/prefs/HBLinkTableCell.m#L69
https://github.com/hbang/libcephei/blob/master/prefs/HBLinkTableCell.m#L77

**Comment by kirb** [comment]
Fixed. (First one doesn’t need it as that method will only ever be called by iOS 7+)
