### ISSUE TITLE
Overriding hb_supportEmailAddress results in a blank email in support form

### ISSUE THREAD

**Issue by leftyfl1p** [hbang/libcephei#21]
Overriding [hb_supportEmailAddress](https://hbang.github.io/libcephei/Classes/HBAboutListController.html#//api/name/hb_supportEmailAddress) results in a blank email in the support form. Using Cephei 1.9. Occurs on iOS 8 and 9.

**Comment by kirb** [comment]
Can you repro on HEAD (clone the repo and `make do`)? Either way, docs are wrong, not sure how I missed that. It should say that's deprecated and to use this instead: https://github.com/hbang/typestatus/blob/db50d3f/prefs/Resources/About.plist#L103-L114

**Comment by leftyfl1p** [comment]
Same thing, even when using the dict you linked, which looks like the only difference is the use of a link cell instead of button?

**Comment by kirb** [comment]
This was fixed (well, worked around) in 1.10.
