### ISSUE TITLE
Settings do not apply within sandboxed applications

### ISSUE THREAD

**Issue by Shade-Zepheri** [hbang/libcephei#22]
I am using HBPreferences to load my prefs into both unsandboxed and sandboxed applications. Even though the reference says it works in sandboxed apps, the preferences do not load for me. I have set up my preferences exactly like the reference.

**Comment by kirb** [comment]
I have [a fix](https://github.com/hbang/libcephei/compare/master...kirb/unfinished/cfprefsd-sandbox-hook) but can’t use it because Substrate blocks injection into cfprefsd. Not sure where to go from here at the moment…

**Comment by Shade-Zepheri** [comment]
I guess I should use another method for prefs?

**Comment by kirb** [comment]
This was fixed in 1.10 with the introduction of an IPC-based workaround.
