### ISSUE TITLE
Perceivable slowness when HBPreferencesIPC is used

### ISSUE THREAD

**Issue by joshuaseltzer** [hbang/libcephei#23]
I noticed this when upgrading from libcephei 1.9 to 1.10 with Opener/MapsOpener installed (versions of those tweaks don't seem to matter).

Test device: iPhone 6s on 9.3.3

**Comment by kirb** [comment]
Does this seem better or worse now? Opener 3.2 now runs within its own daemon; if it's slower then it's most likely an issue with mach ports or LightMessaging being slow and I'm not too sure how that can be solved. Still been meaning to look into this but not sure where to start.

**Comment by joshuaseltzer** [comment]
This update actually sends my device directly into safe mode.  Either "Opener" or "libOpener" are the culprit.  Heres some snippets from my logs when Springboard crashes:

`Feb 28 19:05:39 Josh-iPhone6s SpringBoard[3386] <Warning>: BBObserver: Unable to retrieve section parameters for <com.apple.Passbook>. Using default parameters.`

`Feb 28 19:05:39 Josh-iPhone6s SpringBoard[3386] <Error>: -[__NSDictionaryM dictionary]: unrecognized selector sent to instance 0x1404920b0`

`Feb 28 19:05:39 Josh-iPhone6s SpringBoard[3386] <Error>: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryM dictionary]: unrecognized selector sent to instance 0x1404920b0'
	*** First throw call stack:
	(0x180b72db0 0x1801d7f80 0x180b79c4c 0x180b76bec 0x180a74c5c 0x1037e1d80 0x1037e2560 0x18f0b88c4 0x1825137ac 0x182513618 0x1825139c8 0x180b2909c 0x180b28b30 0x180b26830 0x180a50c50 0x182338088 0x185d3a088 0x100049c08 0x1805ee8b8)`

Uninstalling libOpener (and therefore MapsOpener) stopped the instant safe mode, so I'm assuming the culprit is with the libOpener update and not Celphei.  BTW, same exact device and firmware (iPhone6s on 9.3.3).

EDIT: With just Celphei installed, the delay is not noticeable, but I'm not sure if its due to Opener or Celphei.

**Comment by kirb** [comment]
Oh, there’s a crash on 9.x sorry, please try again after I release the update.

**Comment by joshuaseltzer** [comment]
As of Opener 3.2.1, this appears to be fixed.
