### ISSUE TITLE
Source code of the demo preference pane.

### ISSUE THREAD

**Issue by DaniWinter** [hbang/libcephei#26]
Hi! Where can I find the source code of the demo preference pane from /Library/PreferenceBundles/Cephei.bundle/entry.plist

**Comment by kirb** [comment]
The demo code is in:

* [prefs/Resources/entry.plist](https://github.com/hbang/libcephei/blob/master/prefs/Resources/entry.plist)
* [prefs/Resources/DemoRoot.plist](https://github.com/hbang/libcephei/blob/master/prefs/Resources/DemoRoot.plist)
* [prefs/Resources/DemoAbout.plist](https://github.com/hbang/libcephei/blob/master/prefs/Resources/DemoAbout.plist)
* [prefs/HBDemoRootListController.h](https://github.com/hbang/libcephei/blob/master/prefs/HBDemoRootListController.h)
* [prefs/HBDemoRootListController.m](https://github.com/hbang/libcephei/blob/master/prefs/HBDemoRootListController.m)
* [prefs/HBDemoAboutListController.h](https://github.com/hbang/libcephei/blob/master/prefs/HBDemoAboutListController.h)
* [prefs/HBDemoAboutListController.m](https://github.com/hbang/libcephei/blob/master/prefs/HBDemoAboutListController.m)

I’ll clarify this in the docs, thanks for bringing it up!

**Comment by DaniWinter** [comment]
Great, thanks!

**Comment by Macleykun** [comment]
Believe this issue can be closed.
