### ISSUE TITLE
Crashes Waze when tapping Sound & voice setting

### ISSUE THREAD

**Issue by ghost** [hbang/libcephei#28]
When I try to change the Sound & voice settings in Waze on my iPhone 6S iOS 11.3.1 the app freezes. I tested by disabling all other .dylibs in iCleaner. I am using the tweak Sonus but Waze still crashes even without Sonus so I think it is caused by Cephei somehow.

**Comment by kirb** [comment]
Going to close this as it’s unlikely to be Cephei, and if it was, it should have been fixed in the meantime.
