### ISSUE TITLE
GitHub cell

### ISSUE THREAD

**Issue by kyondev** [hbang/libcephei#35]
Dear Hashbang Productions, please add a GitHub cell (analog to the Twitter cell). 
Or a new custom (social media) cell where the dev can choose the profile picture source url with a customisable subtitle and maybe even custom accessory images

**Comment by kirb** [comment]
A social media cell would be a really good idea. At minimum I could add support for pointing the `icon` key to a URL, that bit won’t be too hard. For GitHub you can just append .png to your profile, i.e. https://github.com/WDKFdev.png.

**Comment by kyondev** [comment]
That would be already amazing! Thank you!

**Comment by kirb** [comment]
Implemented in 1.15, and improved in 1.16.
