### ISSUE TITLE
Can’t compile from source

### ISSUE THREAD

**Issue by ghost** [hbang/libcephei#39]
I downloaded source and didn’t touch any of the files but when I try to compile with theos it says “use of undeclared identifier” with stuff related to iOS 13. 

My reason for compiling is to compile this for x86_64 to work on the iOS simulator but I can’t even get it to compile without changing the ARCHS.

https://pastebin.com/PuiE7SWZ

**Comment by kirb** [comment]
This particular compile error should be fixed with the latest Theos.
