### ISSUE TITLE
App crashing on iOS 13 when tweaks using Cephei try to load

### ISSUE THREAD

**Issue by elihwyma** [hbang/libcephei#40]
When my app launches, for some users, it will crash on launch. It only appears to be other tweaks trying to use Cephei loading with the app causing it to crash, also seems to only happen on u0. When disabling certain tweaks, the app works fine. It should be noted that it only affects some users, and even after installing the tweaks, I couldn't reproduce the issue. A crashlog can be found [here](https://hastebin.com/ajabolasax.sql). 

I could block injection of other tweaks into the app, however I don't feel that's really a solution, and want to know if it's just something I need to fix on my end.

**Comment by kirb** [comment]
Did we come to a conclusion on this? I can’t recall. Either way, the paste has expired, so I’m going to close this. Please reopen if it’s still unresolved.

**Comment by elihwyma** [comment]
No it was never *fixed* per say, my temporary solution is to have a tweak running in Springboard as a wrapper for Cephei, and talk to it with IPC. I'll try and grab another crash log now and put on pastebin.

**Comment by elihwyma** [comment]
From what I've tried, I've been unable to recreate the bug, so I'm not sure if an update fixed it, or I was doing something wrong at first

**Comment by iAdam1n** [comment]
Ok cool, I'll close this issue but feel free to open a new one if it happens again.
