### ISSUE TITLE
issue with link not open in settings 1.15.3

### ISSUE THREAD

**Issue by iKarwan** [hbang/libcephei#41]
issue with sub link when u have it inside settings powered by cephei u can't click it or open it like donation link or github link or pckages link ?

**Comment by iAdam1n** [comment]
What do you mean? Can you send a video to support@hbang.ws?

**Comment by iKarwan** [comment]
sended

**Comment by AzzouQ** [comment]
This bug also apply to `HBStepperTableCell`, making 'plus' and 'minus' buttons un-pressable. Also, on 1.15.3 :
```
<key>label</key>
<string>%i rows</string>
```
 always show 0 for %i, so it's not just 'pressable things' related but it may have a link with values being incorrectly settled, like `url` or `key` idk 🤷

**Comment by kirb** [comment]
Fixed in 1.16.
