### ISSUE TITLE
Stepper cell not working

### ISSUE THREAD

**Issue by giannakillz** [hbang/libcephei#42]
The updates 1.15.2 and 1.15.3 cause an issue where the pictured and circled tweak setting doesn’t respond when trying to change values. 1.15.1 and below has no issues. I’m on latest unc0ver, iOS 13.5 iPhone 8plus. 
![9321D543-5F87-4830-A0A2-C78AEE32EBA8](https://user-images.githubusercontent.com/66619183/91645970-46ae9400-e9ff-11ea-9c1d-404a09d2bbdb.jpeg)

**Comment by vanwijkdave** [comment]
Same problem here, even when using the default configuration from the [docs](https://hbang.github.io/libcephei/Classes/HBStepperTableCell.html)

**Comment by kirb** [comment]
Fixed in 1.16.
