### ISSUE TITLE
[1.15.3] HBTwitterCell not working anymore

### ISSUE THREAD

**Issue by AzzouQ** [hbang/libcephei#43]
Taping on them just don't redirect to Twitter anymore. However, downgrading Cephei to 1.15.1 (didn't try 1.15.2) make them works again.

May be related to #41 idk 🤷

![RPReplay_Final1598807082](https://user-images.githubusercontent.com/60717896/91665152-df264080-eaf3-11ea-810a-21fadb4684ec.gif)

**Comment by kirb** [comment]
Yep, same issue as #41.

**Comment by kirb** [comment]
Fixed in 1.16.
