### ISSUE TITLE
[Safemode] Are iOS 6.1.3 anf iOS 8.4.1 supported?

### ISSUE THREAD

**Issue by Jimmm** [hbang/libcephei#47]
![image](https://user-images.githubusercontent.com/960136/109425805-479a9f80-79fb-11eb-9bfe-f8b5bc0ec1e3.png)
After installing mybloxx I get safe mode, but if I remove cephei there is no safe mode.

**Comment by iAdam1n** [comment]
If you are using "Cephei Tweak Support" from our repo, https://repo.chariz.com, then yes it is. Please try uninstalling all of the 3 items listed there apart from Cephei and see if you still get safe mode.

**Comment by Jimmm** [comment]
I can't, cephei 1.14 (from BigBoss) needs libpackageinfo and techsupport. Or do you mean install it directly from iFile?

**Comment by iAdam1n** [comment]
Whoops, in that case install it all apart from MybloXX.

**Comment by Jimmm** [comment]
Your repo has cephei  1.16, it doesn't need libpackageinfo and techsupport. And there is no safe mode. Problem solved. Thanks for quick reply. Could you update BigBoss package from 1.14 to 1.16?

**Comment by iAdam1n** [comment]
We'll consider it but most of our updates are on our repo now.
