### ISSUE TITLE
Latest 2.0.0 update on rootful palera1n JB seems to break things

### ISSUE THREAD

**Issue by zanodor** [hbang/libcephei#60]
I installed it on a rootful iPad running 15.7.6.  
IPad started getting overheated. Then Obsidian note-taking app and Safari stopped working. I uninstalled and reinstalled the previous version but the problems stayed. I am thinking about restoring RootFS and restoring with iTunes at this point.  
Not 100 percent sure this was the culprit, only 90 percent (I uninstalled nearly every other thing I installed at the same time).

**Comment by qnblackcat** [comment]
Oh no, not again /s

**Comment by kirb** [comment]
Please don’t force install Cephei 2 on rootful - it’s not designed for it and I’m not confident it’ll work correctly. Given what you experienced, it sounds like it definitely doesn’t work. There’s no real functional difference between 1.17.1 and 2.0 anyway, so I’d recommend you just stick to 1.17.1.

**Comment by zanodor** [comment]
But then 1) it shouldn't have been published to Chariz, or 2) users with rootful should have been warned with capital letters, or 3) should not have been enabled to update.  
Something should be done about this. Most people are trigger-happy on buttons that say Upgrade/Update.

**Comment by kirb** [comment]
I don’t know how you installed it on rootful - the package doesn’t install on rootful by default. Are you sure you didn’t do something to allow rootless packages to be installed on your device? (`dpkg --add-architecture iphoneos-arm64` would do that, but you may have run a script or installed a package that ran that command for you.)

**Comment by zanodor** [comment]
Upgraded on Sileo. No warnings.

**Comment by zanodor** [comment]
Any way I can go back not having to restore with iTunes? I have now 1.17 but Chromium/ Electron based apps don't work still.

**Comment by elihwyma** [comment]
> Upgraded on Sileo. No warnings.

Are you using the new palera1n beta 7?

**Comment by zanodor** [comment]
No. I stuck with 1.0.8 because it worked better for me than 1.0.9 and never touched the beta.

**Comment by tale** [comment]
> Any way I can go back not having to restore with iTunes? I have now 1.17.1 but Chromium/ Electron based apps don't work still.

Chromium/Electron? On mobile?

**Comment by zanodor** [comment]
> > Any way I can go back not having to restore with iTunes? I have now 1.17.1 but Chromium/ Electron based apps don't work still.
> 
> Chromium/Electron? On mobile?

I used these terms because they go hand in hand on PC, not sure what they're called on mobile. But browsers don't work and Obsidian starts with a blank screen.

**Comment by elihwyma** [comment]
Sileo uses apt to install and manage packages, unless something is horribly wrong with your configuration it should be impossible to install a rootless package on a rootful install.

**Comment by zanodor** [comment]
> Sileo uses apt to install and manage packages, unless something is horribly wrong with your configuration it should be impossible to install a rootless package on a rootful install.

I used this tut for config:
https://www.reddit.com/r/jailbreak/comments/10xx9pm/tutorial_after_palera1n_jailbreak_must_do/

**Comment by elihwyma** [comment]
> > Sileo uses apt to install and manage packages, unless something is horribly wrong with your configuration it should be impossible to install a rootless package on a rootful install.
> 
> 
> 
> I used this tut for config:
> 
> https://www.reddit.com/r/jailbreak/comments/10xx9pm/tutorial_after_palera1n_jailbreak_must_do/

I would immediately point fingers at the build of RocketBootstrap designed for Coolstar jailbreaks

**Comment by zanodor** [comment]
> > > Sileo uses apt to install and manage packages, unless something is horribly wrong with your configuration it should be impossible to install a rootless package on a rootful install.
> > 
> > 
> > I used this tut for config:
> > https://www.reddit.com/r/jailbreak/comments/10xx9pm/tutorial_after_palera1n_jailbreak_must_do/
> 
> I would immediately point fingers at the build of RocketBootstrap designed for Coolstar jailbreaks

What would you recommend doing instead of those steps?
What does Houston say about the rocket in question? I have no clue what it does.

**Comment by elihwyma** [comment]
> > > > Sileo uses apt to install and manage packages, unless something is horribly wrong with your configuration it should be impossible to install a rootless package on a rootful install.
> 
> > > 
> 
> > > 
> 
> > > I used this tut for config:
> 
> > > https://www.reddit.com/r/jailbreak/comments/10xx9pm/tutorial_after_palera1n_jailbreak_must_do/
> 
> > 
> 
> > I would immediately point fingers at the build of RocketBootstrap designed for Coolstar jailbreaks
> 
> 
> 
> What would you recommend doing instead of those steps?
> 
> What does Houston say about the rocket in question? I have no clue what it does.

Restore rootfs and install palera1n rootless from the 2.0 betas. Look on https://ios.cfw.guide

**Comment by zanodor** [comment]
> > > > > Sileo uses apt to install and manage packages, unless something is horribly wrong with your configuration it should be impossible to install a rootless package on a rootful install.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I used this tut for config:
> > 
> > 
> > > > https://www.reddit.com/r/jailbreak/comments/10xx9pm/tutorial_after_palera1n_jailbreak_must_do/
> > 
> > 
> > > 
> > 
> > 
> > > I would immediately point fingers at the build of RocketBootstrap designed for Coolstar jailbreaks
> > 
> > 
> > What would you recommend doing instead of those steps?
> > What does Houston say about the rocket in question? I have no clue what it does.
> 
> Restore rootfs and install palera1n rootless from the 2.0 betas. Look on https://ios.cfw.guide

I don't really need tweaks. Only local SSH in Shortcuts and Newterm 2, and of course Filza.
I seem to need root.

**Comment by kirb** [comment]
The terminology is confusing, it doesn’t mean you don’t have access to the root user, rather it means we moved the “root” of where jailbreak files are installed from / (the “system root”, which is now protected from being written to on iOS 15+) to /var/jb.

See here for more info: https://www.idownloadblog.com/2022/05/13/f-a-q-rootless-ios-15-jailbreak/

I think what happened is that you actually updated to Cephei **1.17.1**, which was released at the same time as 2.0. I can imagine perhaps some problems arising because of what was instructed in that tutorial. Not sure if we can work around it, or if it’s the right thing to work around it. But we really appreciate it being brought to our attention anyway. We’re going to close this issue right now, but if we see more reports of this we may reopen it.

**Comment by zanodor** [comment]
After finding time to restore and rejailbreak (a couple of times now), I daresay it could be the 10 percent in effect, which means some tweak (couldn't find which one, possibly MilkyWay3 dependent on RocketBootStrap, maybe not) could have caused my issue.  
EDIT:
For safety's sake, I installed 1.17 again and in the meantime, finding issues with app Yoink and tweak Kayoko, I had to start not using those, either.

**Comment by elihwyma** [comment]
It is incredibly likely it was some other tweak, most likely the rocketbootstrap, causing the issue. Even if you somehow managed to install a rootless tweak on a rootful jailbreak it wouldn't inject or do anything. It would just exist on the file system, nothing would know to look for it.

**Comment by zanodor** [comment]
Well, ta for your input. Nice'un.
