### ISSUE TITLE
Unable to Save/Apply Values with HBPreferences methods on Rootless JB (iOS 16.5 palera1n)

### ISSUE THREAD

**Issue by MiRO92** [hbang/libcephei#63]
Hello @kirb,

I hope you're doing well. I'm currently facing an issue with Cephei Preferences specifically on rootless JB (iOS 16.5 palera1n).

The problem I'm encountering is that while the settings values in the preferences bundle seem to work fine, the issue arises when I try to set any value using the HBPreferences methods. It appears that the values I set using the code below do not get saved or applied:

```
HBPreferences* prefs = [[HBPreferences alloc] initWithIdentifier:@"com.miro.yellowpages"];
[prefs setObject:@"string" forKey:@"test"];
```

For instance, setting a value for the key "test" doesn't seem to apply as expected.

I'm wondering if you have any insights or suggestions that could help me resolve this issue. Your assistance would be greatly appreciated.

Thank you!

**Comment by ChristopherA8** [comment]
I'm also having this issue on iOS 16(forgot which version specifically) rootless with palera1n. I have a call to setObject: forKey: in my preferences and it doesn't seem to be working.

**Comment by MiRO92** [comment]
I've just discovered that reading or setting any value using HBPreferences methods won't function on sandboxed apps (such as App Store Apps).

**Comment by kirb** [comment]
Was this issue resolved @MiRO92?
